const PREFIX_API = 'API/';

export const GET_USER_LIST_REQUEST = `${PREFIX_API}REQUEST/USER_LIST_REQUEST`;
export const GET_USER_LIST_SUCCESS = `${PREFIX_API}REQUEST/USER_LIST_SUCCESS`;
export const GET_USER_LIST_FAILURE = `${PREFIX_API}REQUEST/USER_LIST_FAILURE`;
