import {getStatusBarHeight} from 'react-native-status-bar-height';

const statusbarHeight = getStatusBarHeight();

const Colors = {
  success: '#09ce89',
  warning: '#ffd03b',
  error: '#e91e45',
  primary: '#556cff',
  glWhite: '#F2F2F2',
  glGrey: '#707070',
  glLightGrey: '#6A6A6A',
  glBlack: '#2F2F2F',
  glLightBlack: '#383838',
  glOrange: '#FF8C63',
  glOrangeMid: '#FF8B68',
  glOrangeDark: '#FD8C68',
  glButtonOrange: '#FF8C68',
  white: '#FFFFFF',
  glPlaceholder: 'rgba(39, 39, 39, 0.3)',
  glTextLight: 'rgba(39, 39, 39, 0.7)',
  glUserDetail: 'rgba(39, 39, 39, 0.5)',
  glTextGen: '#272727',
  glTextDisable: '#808080',
  glTextDark: '#BEBEBE',
  glBackgroundBlack: 'rgba(39, 39, 39, 0.17)',
  glLine: 'rgba(39, 39, 39, 0.1)',
  glNoToDoText: '#B6B6B6',
  glOrangeGrad1: '#FF9F68',
  glOrangeGrad2: '#FFBE7D',
  glYellowGrad1: '#F6E18F',
  glYellowGrad2: '#F6EF8F',
  glYellowGrad3: '#EAF68F',
  glYellowGrad4: '#D9F68F',
  glGreenGrad1: '#ABF0AB',
  glGreenGrad2: '#78EF9E',
  glGreenGrad3: '#78EFC8',
  glGreenLight: '#E1FFEF',
  glClpUnits: '#E5E5E5',
  glClassAttend: '#B5E8AD',
  glCorrect: '#4CC367',
  glWrong: '#E43344',
  glCorrectDot: '#17A2B8',
  glWrongArrowDown: '#721c24',
  glWrongBackground: '#f5c6cb',
  glCorrectArrowDown: '#155724',
  glCorrectBackground: '#c3e6cb',
  glCustomCancel: '#007AFF',
  glDivider: '#d8d8e2',
};

const Fonts = {
  muliBlack: 'Muli-Black',
  muliBlackItalic: 'Muli-BlackItalic',
  muliBold: 'Muli-Bold',
  muliBoldItalic: 'Muli-BoldItalic',
  muliExtraBold: 'Muli-ExtraBold',
  muliExtraBoldItalic: 'Muli-ExtraBoldItalic',
  muliExtraLight: 'Muli-ExtraLight',
  muliExtraLightItalic: 'Muli-ExtraLightItalic',
  muliLight: 'Muli-Light',
  muliLightItalic: 'Muli-LightItalic',
  muliRegular: 'Muli-Regular',
  muliRegularItalic: 'Muli-RegularItalic',
  muliSemiBold: 'Muli-SemiBold',
  muliSemiBoldItalic: 'Muli-SemiBoldItalic',
};

module.exports = {
  Fonts,
  Colors,
};
