const PREFIX_INCREMENT = 'INCREMENT/';
const PREFIX_INCREMENT_TEXT = 'INCREMENT_TEXT/';

export const UPDATE_INCREMENT = `${PREFIX_INCREMENT}REQUEST/INCREMENT`;
export const UPDATE_INCREMENT_TEXT = `${PREFIX_INCREMENT_TEXT}REQUEST/INCREMENT_TEXT`;
